// <auto-generated />
using EntityFrameworkTest.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace EntityFrameworkTest.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20180501215027_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("EntityFrameworkTest.Models.Organization", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<DateTime>("Created");

                    b.Property<DateTime>("Modified");

                    b.HasKey("ID");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("EntityFrameworkTest.Models.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<DateTime>("Created");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("Name");

                    b.Property<int?>("OwningGroupID");

                    b.Property<int?>("ProductGroupIDID");

                    b.HasKey("ID");

                    b.HasIndex("OwningGroupID");

                    b.HasIndex("ProductGroupIDID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("EntityFrameworkTest.Models.ProductGroup", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<DateTime>("Created");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("ProductGroup");
                });

            modelBuilder.Entity("EntityFrameworkTest.Models.Product", b =>
                {
                    b.HasOne("EntityFrameworkTest.Models.ProductGroup", "OwningGroup")
                        .WithMany()
                        .HasForeignKey("OwningGroupID");

                    b.HasOne("EntityFrameworkTest.Models.ProductGroup", "ProductGroupID")
                        .WithMany()
                        .HasForeignKey("ProductGroupIDID");
                });
#pragma warning restore 612, 618
        }
    }
}
