version: '3.1'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: foo
      POSTGRES_USER: wft
    volumes:
      - entity-test:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  entity-test:

 # symmetric:
 #   image: jumpmind/symmetricds
 #   depends_on:
 #     - db
 #   volumes:
 #     - c:/Users/neil/docker/symmetric/client4/sym-engines:/opt/symmetric-ds/engines
 #   ports:
 #     - 31415:31415

